-- ============================================================================
-- categories.sql — СГЕНЕРИРОВАННЫЙ ФАЙЛ, РУКАМИ НЕ ПРАВИТЬ
--
-- Источник: data/categories.ru.json
-- Генератор: node scripts/build-seed.mjs
--
-- Групп: 12, категорий: 87, всего строк: 99
-- ============================================================================

insert into public.item_categories (id, parent_id, name_ru, icon, sort_order, default_energy_mode, default_power_w, default_standby_w, default_duty_cycle, default_hours_per_day, default_kwh_per_cycle, default_cycles_per_week, label_unit, default_warranty_months, default_service_interval_days)
values
  ('kitchen', null, 'Кухня', '🍳', 10, null, null, null, null, null, null, null, null, null, null),
  ('laundry', null, 'Стирка и уборка', '🧺', 20, null, null, null, null, null, null, null, null, null, null),
  ('climate', null, 'Климат', '🌡', 30, null, null, null, null, null, null, null, null, null, null),
  ('water', null, 'Вода и отопление', '🚿', 40, null, null, null, null, null, null, null, null, null, null),
  ('electronics', null, 'Электроника', '💻', 50, null, null, null, null, null, null, null, null, null, null),
  ('lighting', null, 'Освещение', '💡', 60, null, null, null, null, null, null, null, null, null, null),
  ('furniture', null, 'Мебель', '🛋', 70, null, null, null, null, null, null, null, null, null, null),
  ('tools', null, 'Инструменты и хозяйство', '🔧', 80, null, null, null, null, null, null, null, null, null, null),
  ('personal', null, 'Личный уход', '🪥', 90, null, null, null, null, null, null, null, null, null, null),
  ('outdoor', null, 'Улица и транспорт', '🚗', 100, null, null, null, null, null, null, null, null, null, null),
  ('safety', null, 'Безопасность и коммуникации', '🛡', 110, null, null, null, null, null, null, null, null, null, null),
  ('other', null, 'Прочее', '📦', 120, null, null, null, null, null, null, null, null, null, null),
  ('kitchen.fridge', 'kitchen', 'Холодильник', '🧊', 10, 'typical', 150, null, 0.3, null, null, null, 'kwh_year', 24, null),
  ('kitchen.freezer', 'kitchen', 'Морозильная камера', '❄️', 20, 'typical', 120, null, 0.35, null, null, null, 'kwh_year', 24, null),
  ('kitchen.stove', 'kitchen', 'Плита', '🔥', 30, 'power_hours', 2000, null, null, 1, null, null, null, 24, null),
  ('kitchen.oven', 'kitchen', 'Духовка', '🥧', 40, 'per_cycle', null, null, null, null, 1.2, 3, null, 24, null),
  ('kitchen.hood', 'kitchen', 'Вытяжка', '💨', 50, 'power_hours', 120, null, null, 1, null, null, null, 24, 180),
  ('kitchen.microwave', 'kitchen', 'Микроволновка', '📻', 60, 'per_cycle', null, 1.5, null, null, 0.09, 14, null, 24, null),
  ('kitchen.dishwasher', 'kitchen', 'Посудомоечная машина', '🍽', 70, 'per_cycle', null, null, null, null, 1, 5, 'kwh_100cycles', 24, 180),
  ('kitchen.kettle', 'kitchen', 'Электрочайник', '🫖', 80, 'per_cycle', null, null, null, null, 0.1, 21, null, 12, null),
  ('kitchen.coffee', 'kitchen', 'Кофемашина', '☕', 90, 'per_cycle', null, 1, null, null, 0.05, 14, null, 24, 180),
  ('kitchen.multicooker', 'kitchen', 'Мультиварка', '🍲', 100, 'per_cycle', null, null, null, null, 0.4, 4, null, 12, null),
  ('kitchen.blender', 'kitchen', 'Блендер', '🥤', 110, 'per_cycle', null, null, null, null, 0.02, 7, null, 12, null),
  ('kitchen.mixer', 'kitchen', 'Миксер', '🧁', 120, 'per_cycle', null, null, null, null, 0.02, 2, null, 12, null),
  ('kitchen.toaster', 'kitchen', 'Тостер', '🍞', 130, 'per_cycle', null, null, null, null, 0.04, 7, null, 12, null),
  ('kitchen.meatgrinder', 'kitchen', 'Мясорубка', '🥩', 140, 'per_cycle', null, null, null, null, 0.05, 2, null, 12, null),
  ('kitchen.juicer', 'kitchen', 'Соковыжималка', '🍊', 150, 'per_cycle', null, null, null, null, 0.03, 2, null, 12, null),
  ('kitchen.waterfilter', 'kitchen', 'Фильтр для воды', '💧', 160, null, null, null, null, null, null, null, null, null, 180),
  ('laundry.washer', 'laundry', 'Стиральная машина', '🌀', 10, 'per_cycle', null, null, null, null, 0.8, 4, 'kwh_100cycles', 24, 365),
  ('laundry.dryer', 'laundry', 'Сушильная машина', '🌬', 20, 'per_cycle', null, null, null, null, 2, 2, 'kwh_100cycles', 24, 365),
  ('laundry.washer_dryer', 'laundry', 'Стирально-сушильная машина', '🌀', 30, 'per_cycle', null, null, null, null, 1.6, 3, 'kwh_100cycles', 24, 365),
  ('laundry.vacuum', 'laundry', 'Пылесос', '🧹', 40, 'per_cycle', null, null, null, null, 0.15, 2, null, 24, 180),
  ('laundry.robot_vacuum', 'laundry', 'Робот-пылесос', '🤖', 50, 'per_cycle', null, null, null, null, 0.06, 7, null, 24, 90),
  ('laundry.iron', 'laundry', 'Утюг', '👔', 60, 'per_cycle', null, null, null, null, 0.2, 2, null, 12, null),
  ('laundry.steamer', 'laundry', 'Отпариватель', '♨️', 70, 'per_cycle', null, null, null, null, 0.1, 2, null, 12, null),
  ('climate.ac', 'climate', 'Кондиционер', '🧊', 10, 'power_hours', 900, null, null, 5, null, null, null, 36, 365),
  ('climate.heater', 'climate', 'Обогреватель', '🔥', 20, 'power_hours', 1500, null, null, 6, null, null, null, 12, null),
  ('climate.fan', 'climate', 'Вентилятор', '🌀', 30, 'power_hours', 50, null, null, 6, null, null, null, 12, null),
  ('climate.humidifier', 'climate', 'Увлажнитель воздуха', '💨', 40, 'power_hours', 30, null, null, 8, null, null, null, 12, 90),
  ('climate.dehumidifier', 'climate', 'Осушитель воздуха', '💦', 50, 'power_hours', 300, null, null, 4, null, null, null, 24, 180),
  ('climate.air_purifier', 'climate', 'Очиститель воздуха', '🌿', 60, 'typical', 30, null, 0.5, null, null, null, null, 24, 180),
  ('climate.heated_floor', 'climate', 'Тёплый пол', '🔆', 70, 'power_hours', 800, null, null, 8, null, null, null, 60, null),
  ('climate.towel_dryer', 'climate', 'Полотенцесушитель', '🧻', 80, 'typical', 60, null, 1, null, null, null, null, 24, null),
  ('water.boiler', 'water', 'Бойлер', '🛢', 10, 'typical', 2000, null, 0.12, null, null, null, null, 24, 365),
  ('water.gas_boiler', 'water', 'Газовый котёл', '🔥', 20, 'typical', 100, null, 0.3, null, null, null, null, 24, 365),
  ('water.pump', 'water', 'Насос', '⚙️', 30, 'typical', 400, null, 0.05, null, null, null, null, 24, null),
  ('water.filter_main', 'water', 'Магистральный фильтр', '🧯', 40, null, null, null, null, null, null, null, null, null, 180),
  ('water.meter', 'water', 'Счётчик воды', '🔢', 50, null, null, null, null, null, null, null, null, null, 1460),
  ('water.radiator', 'water', 'Радиатор отопления', '🌡', 60, null, null, null, null, null, null, null, null, null, null),
  ('electronics.tv', 'electronics', 'Телевизор', '📺', 10, 'power_hours', 100, 0.5, null, 4, null, null, 'kwh_1000h', 24, null),
  ('electronics.monitor', 'electronics', 'Монитор', '🖥', 20, 'power_hours', 30, 0.5, null, 6, null, null, 'kwh_1000h', 24, null),
  ('electronics.desktop', 'electronics', 'Настольный компьютер', '🖥', 30, 'power_hours', 200, 2, null, 6, null, null, null, 24, null),
  ('electronics.laptop', 'electronics', 'Ноутбук', '💻', 40, 'power_hours', 50, null, null, 6, null, null, null, 24, null),
  ('electronics.router', 'electronics', 'Роутер', '📶', 50, 'typical', 8, null, 1, null, null, null, null, 12, null),
  ('electronics.console', 'electronics', 'Игровая приставка', '🎮', 60, 'power_hours', 150, 1, null, 2, null, null, null, 12, null),
  ('electronics.speaker', 'electronics', 'Аудиосистема', '🔊', 70, 'power_hours', 20, 1, null, 3, null, null, null, 12, null),
  ('electronics.smart_speaker', 'electronics', 'Умная колонка', '🗣', 80, 'typical', 3, null, 1, null, null, null, null, 12, null),
  ('electronics.printer', 'electronics', 'Принтер', '🖨', 90, 'per_cycle', null, 2, null, null, 0.01, 3, null, 12, 365),
  ('electronics.projector', 'electronics', 'Проектор', '📽', 100, 'power_hours', 250, null, null, 1, null, null, null, 24, 365),
  ('electronics.nas', 'electronics', 'NAS или домашний сервер', '🗄', 110, 'typical', 30, null, 1, null, null, null, null, 24, null),
  ('electronics.ups', 'electronics', 'Источник бесперебойного питания', '🔋', 120, 'typical', 10, null, 1, null, null, null, null, 24, 1095),
  ('lighting.ceiling', 'lighting', 'Потолочный свет', '💡', 10, 'power_hours', 40, null, null, 5, null, null, null, null, null),
  ('lighting.lamp', 'lighting', 'Настольная лампа', '🛋', 20, 'power_hours', 10, null, null, 4, null, null, null, null, null),
  ('lighting.led_strip', 'lighting', 'Светодиодная лента', '🌈', 30, 'power_hours', 25, null, null, 4, null, null, null, null, null),
  ('lighting.outdoor', 'lighting', 'Уличный светильник', '🏮', 40, 'power_hours', 20, null, null, 8, null, null, null, null, null),
  ('furniture.sofa', 'furniture', 'Диван', '🛋', 10, null, null, null, null, null, null, null, null, null, null),
  ('furniture.bed', 'furniture', 'Кровать', '🛏', 20, null, null, null, null, null, null, null, null, null, null),
  ('furniture.wardrobe', 'furniture', 'Шкаф', '🚪', 30, null, null, null, null, null, null, null, null, null, null),
  ('furniture.table', 'furniture', 'Стол', '🪑', 40, null, null, null, null, null, null, null, null, null, null),
  ('furniture.chair', 'furniture', 'Стул или кресло', '🪑', 50, null, null, null, null, null, null, null, null, null, null),
  ('furniture.kitchen_set', 'furniture', 'Кухонный гарнитур', '🗄', 60, null, null, null, null, null, null, null, null, null, null),
  ('furniture.mirror', 'furniture', 'Зеркало', '🪞', 70, null, null, null, null, null, null, null, null, null, null),
  ('tools.drill', 'tools', 'Дрель или шуруповёрт', '🔩', 10, 'per_cycle', null, null, null, null, 0.05, 0.5, null, 24, null),
  ('tools.sewing', 'tools', 'Швейная машина', '🧵', 20, 'per_cycle', null, null, null, null, 0.05, 1, null, 24, 730),
  ('tools.welder', 'tools', 'Сварочный аппарат', '⚡', 30, 'per_cycle', null, null, null, null, 0.5, 0.2, null, 24, null),
  ('tools.compressor', 'tools', 'Компрессор', '🌬', 40, 'per_cycle', null, null, null, null, 0.3, 0.5, null, 24, null),
  ('tools.ladder', 'tools', 'Стремянка', '🪜', 50, null, null, null, null, null, null, null, null, null, null),
  ('tools.toolbox', 'tools', 'Набор инструментов', '🧰', 60, null, null, null, null, null, null, null, null, null, null),
  ('personal.hairdryer', 'personal', 'Фен', '💇', 10, 'per_cycle', null, null, null, null, 0.05, 7, null, 12, null),
  ('personal.shaver', 'personal', 'Электробритва', '🪒', 20, 'per_cycle', null, null, null, null, 0.01, 5, null, 24, null),
  ('personal.toothbrush', 'personal', 'Электрическая зубная щётка', '🪥', 30, 'per_cycle', null, null, null, null, 0.005, 14, null, 24, 90),
  ('personal.scales', 'personal', 'Весы', '⚖️', 40, null, null, null, null, null, null, null, null, 12, null),
  ('outdoor.car', 'outdoor', 'Автомобиль', '🚗', 10, null, null, null, null, null, null, null, null, null, 365),
  ('outdoor.bike', 'outdoor', 'Велосипед', '🚲', 20, null, null, null, null, null, null, null, null, null, 365),
  ('outdoor.escooter', 'outdoor', 'Электросамокат', '🛴', 30, 'per_cycle', null, null, null, null, 0.5, 3, null, 12, 365),
  ('outdoor.lawnmower', 'outdoor', 'Газонокосилка', '🌱', 40, 'per_cycle', null, null, null, null, 0.3, 1, null, 24, 365),
  ('outdoor.grill', 'outdoor', 'Гриль или мангал', '🍖', 50, null, null, null, null, null, null, null, null, null, null),
  ('safety.smoke_detector', 'safety', 'Датчик дыма', '🚨', 10, null, null, null, null, null, null, null, null, null, 365),
  ('safety.co_detector', 'safety', 'Датчик угарного газа', '☠️', 20, null, null, null, null, null, null, null, null, null, 365),
  ('safety.fire_extinguisher', 'safety', 'Огнетушитель', '🧯', 30, null, null, null, null, null, null, null, null, null, 365),
  ('safety.camera', 'safety', 'Камера видеонаблюдения', '📹', 40, 'typical', 5, null, 1, null, null, null, null, 24, null),
  ('safety.doorbell', 'safety', 'Домофон или видеозвонок', '🔔', 50, 'typical', 3, null, 1, null, null, null, null, 24, null),
  ('safety.alarm', 'safety', 'Сигнализация', '🚔', 60, 'typical', 10, null, 1, null, null, null, null, 24, 365),
  ('safety.electrical_panel', 'safety', 'Электрощиток', '⚡', 70, null, null, null, null, null, null, null, null, null, null),
  ('safety.water_valve', 'safety', 'Вентиль перекрытия воды', '🚰', 80, null, null, null, null, null, null, null, null, null, null),
  ('safety.gas_valve', 'safety', 'Газовый кран', '🔧', 90, null, null, null, null, null, null, null, null, null, null),
  ('other.plant', 'other', 'Растение', '🪴', 10, null, null, null, null, null, null, null, null, null, 7),
  ('other.pet', 'other', 'Для питомца', '🐾', 20, null, null, null, null, null, null, null, null, null, null),
  ('other.misc', 'other', 'Прочее', '📦', 30, null, null, null, null, null, null, null, null, null, null)
on conflict (id) do update set
  parent_id                     = excluded.parent_id,
  name_ru                       = excluded.name_ru,
  icon                          = excluded.icon,
  sort_order                    = excluded.sort_order,
  default_energy_mode           = excluded.default_energy_mode,
  default_power_w               = excluded.default_power_w,
  default_standby_w             = excluded.default_standby_w,
  default_duty_cycle            = excluded.default_duty_cycle,
  default_hours_per_day         = excluded.default_hours_per_day,
  default_kwh_per_cycle         = excluded.default_kwh_per_cycle,
  default_cycles_per_week       = excluded.default_cycles_per_week,
  label_unit                    = excluded.label_unit,
  default_warranty_months       = excluded.default_warranty_months,
  default_service_interval_days = excluded.default_service_interval_days;
